// Map of weather codes identical to the backend mapping
// TODO?: fetch weather codes from the backend API
export const weatherCodes = new Map([
  [0, "Bezchmurnie"],
  [1, "Przeważnie bezchmurnie"],
  [2, "Częściowe zachmurzenie"],
  [3, "Pochmurnie"],
  [45, "Mgła"],
  [48, "Szadź"],
  [51, "Lekka mżawka"],
  [53, "Umiarkowana mżawka"],
  [55, "Gęsta mżawka"],
  [56, "Lekka marznąca mżawka"],
  [57, "Gęsta marznąca mżawka"],
  [61, "Lekki deszcz"],
  [63, "Umiarkowany deszcz"],
  [65, "Silny deszcz"],
  [66, "Lekki marznący deszcz"],
  [67, "Silny marznący deszcz"],
  [71, "Lekki śnieg"],
  [73, "Umiarkowany śnieg"],
  [75, "Silny śnieg"],
  [77, "Ziarna śniegu"],
  [80, "Lekka przelotna ulewa"],
  [81, "Umiarkowana przelotna ulewa"],
  [82, "Gwałtowna przelotna ulewa"],
  [85, "Lekkie przelotne opady śniegu"],
  [86, "Silne przelotne opady śniegu"],
  [95, "Burza"],
  [96, "Burza z lekkim gradem"],
  [99, "Burza z silnym gradem"],
]);
