export const weather_codes = new Map([
    [0, "Clear"],
    [1, "Mainly Clear"],
    [2, "Partly Cloudy"],
    [3, "Overcast"],
    [45, "Fog"],
    [48, "Rime Fog"],
    [51, "Light Drizzle"],
    [53, "Moderate Drizzle"],
    [55, "Dense Drizzle"],
    [56, "Light Freezing Drizzle"],
    [57, "Dense Freezing Drizzle"],
    [61, "Slight Rain"],
    [63, "Moderate Rain"],
    [65, "Heavy Rain"],
    [66, "Light Freezing Rain"],
    [67, "Heavy Freezing Rain"],
    [71, "Light Snow"],
    [73, "Moderate Snow"],
    [75, "Heavy Snow"],
    [77, "Snow Grains"],
    [80, "Slight Rain Shower"],
    [81, "Moderate Rain Shower"],
    [82, "Violent Rain Shower"],
    [85, "Slight Snow Shower"],
    [86, "Heavy Snow Shower"],
    [95, "Thunderstorm"],
    [96, "Thunderstorm, Slight Hail"],
    [99, "Thunderstorm, Heavy Hail"]
])